### ISSUE TITLE
fauxmoESP does not work

### ISSUE THREAD

**Issue by pvint** [vintlabs/fauxmoESP#30]
**[Original report](https://bitbucket.org/xoseperez/fauxmoesp/issue/30) by Marvin Michel (Bitbucket: [marfbuilds](https://bitbucket.org/marfbuilds), GitHub: [marfbuilds](https://github.com/marfbuilds)).**

----------------------------------------

Hello 
I have a Problem with this example code.

```
#!arduino

#include <Arduino.h>
#include <ESP8266WiFi.h>
#include "fauxmoESP.h"
#include "credentials.h"

#define SERIAL_BAUDRATE                 115200
#define LED                             2

fauxmoESP fauxmo;

// -----------------------------------------------------------------------------
// Wifi
// -----------------------------------------------------------------------------

void wifiSetup() {

    // Set WIFI module to STA mode
    WiFi.mode(WIFI_STA);

    // Connect
    Serial.printf("[WIFI] Connecting to %s ", WIFI_SSID);
    WiFi.begin(WIFI_SSID, WIFI_PASS);

    // Wait
    while (WiFi.status() != WL_CONNECTED) {
        Serial.print(".");
        delay(100);
    }
    Serial.println();

    // Connected!
    Serial.printf("[WIFI] STATION Mode, SSID: %s, IP address: %s\n", WiFi.SSID().c_str(), WiFi.localIP().toString().c_str());

}

void setup() {

    // Init serial port and clean garbage
    Serial.begin(SERIAL_BAUDRATE);
    Serial.println();
    Serial.println();

    // Wifi
    wifiSetup();

    // LED
    pinMode(LED, OUTPUT);
    digitalWrite(LED, HIGH);

    // You can enable or disable the library at any moment
    // Disabling it will prevent the devices from being discovered and switched
    fauxmo.enable(true);

    // Add virtual devices
    fauxmo.addDevice("switch one");
	//fauxmo.addDevice("switch two"); // You can add more devices
	//fauxmo.addDevice("switch three");

    // fauxmoESP 2.0.0 has changed the callback signature to add the device_id, this WARRANTY
    // it's easier to match devices to action without having to compare strings.
    fauxmo.onSetState([](unsigned char device_id, const char * device_name, bool state) {
        Serial.printf("[MAIN] Device #%d (%s) state: %s\n", device_id, device_name, state ? "ON" : "OFF");
        digitalWrite(LED, !state);
    });

    // Callback to retrieve current state (for GetBinaryState queries)
    fauxmo.onGetState([](unsigned char device_id, const char * device_name) {
        return digitalRead(LED) == HIGH;
    });

}

void loop() {

    // Since fauxmoESP 2.0 the library uses the "compatibility" mode by
    // default, this means that it uses WiFiUdp class instead of AsyncUDP.
    // The later requires the Arduino Core for ESP8266 staging version
    // whilst the former works fine with current stable 2.3.0 version.
    // But, since it's not "async" anymore we have to manually poll for UDP
    // packets
    fauxmo.handle();

    static unsigned long last = millis();
    if (millis() - last > 5000) {
        last = millis();
        Serial.printf("[MAIN] Free heap: %d bytes\n", ESP.getFreeHeap());
    }

}
```

The problem is :

```

Archiving built core (caching) in: C:\Users\test\AppData\Local\Temp\arduino_cache_52241\core\core_esp8266_esp8266_nodemcu_CpuFrequency_80,UploadSpeed_115200,FlashSize_4M3M_50adef9056d4f232fdad5368e81ce5a5.a
sketch\fauxmoESP_Basic.ino.cpp.o: In function `wifiSetup()':

C:\Users\test\Documents\Arduino\libraries\xoseperez-fauxmoesp-13e3da6679ed\src/fauxmoESP.h:70: undefined reference to `fauxmoESP::handle()'

C:\Users\test\Documents\Arduino\libraries\xoseperez-fauxmoesp-13e3da6679ed\src/fauxmoESP.h:70: undefined reference to `fauxmoESP::handle()'

sketch\fauxmoESP_Basic.ino.cpp.o: In function `loop':

C:\Users\test\Documents\Arduino\libraries\xoseperez-fauxmoesp-13e3da6679ed\src/fauxmoESP.h:70: undefined reference to `fauxmoESP::enable(bool)'

C:\Users\test\Documents\Arduino\libraries\xoseperez-fauxmoesp-13e3da6679ed\src/fauxmoESP.h:70: undefined reference to `fauxmoESP::addDevice(char const*)'

sketch\fauxmoESP_Basic.ino.cpp.o:(.text.setup+0x69): undefined reference to `fauxmoESP::enable(bool)'

sketch\fauxmoESP_Basic.ino.cpp.o: In function `setup':

C:\Users\test\Documents\Arduino\libraries\xoseperez-fauxmoesp-13e3da6679ed\src/fauxmoESP.h:70: undefined reference to `fauxmoESP::addDevice(char const*)'

sketch\fauxmoESP_Basic.ino.cpp.o: In function `~function':

C:\Users\test\Documents\Arduino\libraries\xoseperez-fauxmoesp-13e3da6679ed\src/fauxmoESP.h:70: undefined reference to `fauxmoESP::fauxmoESP(unsigned int)'

sketch\fauxmoESP_Basic.ino.cpp.o: In function `_M_init_functor':

C:\Users\test\Documents\Arduino\libraries\xoseperez-fauxmoesp-13e3da6679ed\examples\fauxmoESP_Basic/fauxmoESP_Basic.ino:89: undefined reference to `fauxmoESP::fauxmoESP(unsigned int)'

collect2.exe: error: ld returned 1 exit status

```
Thanks for helping me !
Marvin
