### ISSUE TITLE
" 'class fauxmoESP' has no member named 'getColormode " after Update to 3.04?

### ISSUE THREAD

**Issue by MoL0815** [vintlabs/fauxmoESP#202]
Made update from 3.2.0 to 3.4.0  in Arduino 1.8.15; now I get this error and do not know how to fix ist?
Any suggestions?

**Comment by MoL0815** [comment]
Argh, wrong branch!!
