### ISSUE TITLE
'class fauxmoESP' has no member named 'onGetState'

### ISSUE THREAD

**Issue by pvint** [vintlabs/fauxmoESP#99]
**[Original report](https://bitbucket.org/xoseperez/fauxmoesp/issue/99) by federico lucca (Bitbucket: [federicolucca](https://bitbucket.org/federicolucca), GitHub: [federicolucca](https://github.com/federicolucca)).**

----------------------------------------

Hi,

This library is a great work!!!

I am trying to work with ESP32, library version 3.1.0.

Every thing work fine but i am not able to use the “`onGetState`“  method. Could have be removed or deprecated? then which one can i use instead?

‌

Thanks

Federico

**Comment by pvint** [comment]
@federicolucca 
I've recently taken over maintenance of this project. Can you tell me what you are trying to accomplish?

Paul
